/*
*  Pacemaker4Mbed (c) 2014 Ariel Eizenberg - arieleiz@seas.upenn.edu.
*  Developed for UPENN CIS 541 course project - verifiable pacemaker.
*
*    This file is part of Pacemaker4Mbed. You can redistribute it and/or modify
*    it under the terms of the Academic Free License 3.0
*	  (http://opensource.org/licenses/AFL-3.0).
*
*/

// THIS FILE WAS AUTO GENERATED BY model2mbed.exe DO NOT MODIFY!!!

#include "ModelImpl.h"

namespace Model {
// Channels
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_press; // chan press


struct SYSTEM_VARIABLES
    {
         int __unused__;
        clk clk_GLOBAL_y;
       public:  SYSTEM_VARIABLES() :
 __unused__(0){
}
       private: SYSTEM_VARIABLES(const SYSTEM_VARIABLES& other);
       private: SYSTEM_VARIABLES& operator=(const SYSTEM_VARIABLES& other);
    };

extern SYSTEM_VARIABLES SystemVariables;

// Process - Light

extern ModelImpl::TRANSITION_ENTRY Light_TRANS_bright__off__0;
extern ModelImpl::TRANSITION_ENTRY Light_TRANS_low__bright__0;
extern ModelImpl::TRANSITION_ENTRY Light_TRANS_low__off__0;
extern ModelImpl::TRANSITION_ENTRY Light_TRANS_off__low__0;
extern ModelImpl::STATE_ENTRY Light_STATE_bright;
extern ModelImpl::STATE_ENTRY Light_STATE_low;
extern ModelImpl::STATE_ENTRY Light_STATE_off;
extern ModelImpl::PROCESS_ENTRY Light_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE Light_PROCESS_STATE;



} // namespace

// initialize the dispatcher:
//    ModelImpl::Dispatcher disp;
//    disp.set_clock_multiplier(1000 /*us*/);
//    #ifdef _DEBUG
//    disp.init_debug(&pc);
//    #endif
//
// add events. examples:
//    disp.set_channel_action(&Model::Template_CHANNEL_VAR_led, LED1, ModelImpl::SendChannelModePulseUp, 250000);
//    disp.set_channel_action(&Model::Template_CHANNEL_VAR_manual, LED1, ModelImpl::SendChannelModeToggle);
//    disp.set_receive_input(&Model::GLOBAL_CHANNEL_VAR_press, p7, ModelImpl::ReceiveChannelInterruptRise);
//
// Tip: use just the templates you want in the code:
//    disp.add_process(&Model::Light_PROCESS_STATE);
//
// and finally run:
//    disp.run();

