#pragma once
// THIS FILE WAS AUTO GENERATED BY model2mbed.exe DO NOT MODIFY!!!

#include "ModelImpl.h"

namespace Model {
// Channels
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_Apace; // brodcast chan Apace
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_Vpace; // brodcast chan Vpace
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_Asignal; // brodcast chan Asignal
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_Vsignal; // brodcast chan Vsignal
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_AlarmH; // brodcast chan AlarmH
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_AlarmL; // brodcast chan AlarmL
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_NoAlarm; // brodcast chan NoAlarm
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_Asense; // urgent brodcast chan Asense
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_Vsense; // urgent brodcast chan Vsense
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_PMmodechange; // urgent brodcast chan PMmodechange
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_testPM_normal; // urgent brodcast chan testPM_normal
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_testPM_sleep; // urgent brodcast chan testPM_sleep
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_testPM_sports; // urgent brodcast chan testPM_sports
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_testPM_manual; // urgent brodcast chan testPM_manual
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_testPM_gen_0; // urgent brodcast chan testPM_gen[0,3]
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_testPM_gen_1; // urgent brodcast chan testPM_gen[0,3]
extern ModelImpl::SYNCHRONIZATION_CHANNEL GLOBAL_CHANNEL_VAR_testPM_gen_2; // urgent brodcast chan testPM_gen[0,3]


struct SYSTEM_VARIABLES
    {
        clk clk_GLOBAL_clk_aa;
        clk clk_GLOBAL_clk_pvarp;
        const int int_GLOBAL_Sleep_LRI;
        const int int_GLOBAL_Sleep_URI;
        const int int_GLOBAL_Normal_LRI;
        const int int_GLOBAL_Normal_URI;
        const int int_GLOBAL_Sports_LRI;
        const int int_GLOBAL_Sports_URI;
        const int int_GLOBAL_Low_AVI;
        const int int_GLOBAL_Max_AVIExt;
        const int int_GLOBAL_AVIExt_Step;
        const int int_GLOBAL_Low_VRP;
        const int int_GLOBAL_Low_PVARP;
        const int int_GLOBAL_Low_PVAB;
        const int int_GLOBAL_High_MSTI;
        int int_GLOBAL_pmmode;
        int int_GLOBAL_cur_avi;
        int int_GLOBAL_cur_avi_ext;
        int int_GLOBAL_cur_pvarp;
        int int_GLOBAL_cur_pvab;
        int int_GLOBAL_cur_vrp;
        int int_GLOBAL_cur_uri;
        int int_GLOBAL_cur_lri;
        int int_GLOBAL_cur_msti;
        clk clk_PM_Sensor_V_clkt;
        clk clk_PM_DisplayAndAlarm_t;
        int int_PM_DisplayAndAlarm_aa_count;
        int int_PM_DisplayAndAlarm_aa_rate;
         int __unused__;
       public:  SYSTEM_VARIABLES() :
        int_GLOBAL_Sleep_LRI(2000),
        int_GLOBAL_Sleep_URI(1000),
        int_GLOBAL_Normal_LRI(1500),
        int_GLOBAL_Normal_URI(600),
        int_GLOBAL_Sports_LRI(600),
        int_GLOBAL_Sports_URI(342),
        int_GLOBAL_Low_AVI(30),
        int_GLOBAL_Max_AVIExt(50),
        int_GLOBAL_AVIExt_Step(5),
        int_GLOBAL_Low_VRP(150),
        int_GLOBAL_Low_PVARP(150),
        int_GLOBAL_Low_PVAB(10),
        int_GLOBAL_High_MSTI(10000),
        int_GLOBAL_pmmode(0),
        int_GLOBAL_cur_avi(30),
        int_GLOBAL_cur_avi_ext(0),
        int_GLOBAL_cur_pvarp(150),
        int_GLOBAL_cur_pvab(10),
        int_GLOBAL_cur_vrp(150),
        int_GLOBAL_cur_uri(600),
        int_GLOBAL_cur_lri(1500),
        int_GLOBAL_cur_msti(10000),
        int_PM_DisplayAndAlarm_aa_count(0),
        int_PM_DisplayAndAlarm_aa_rate(0),
 __unused__(0){
}
       private: SYSTEM_VARIABLES(const SYSTEM_VARIABLES& other);
       private: SYSTEM_VARIABLES& operator=(const SYSTEM_VARIABLES& other);
    };

extern SYSTEM_VARIABLES SystemVariables;

// Process - PM_ModeSwitch

extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Init__Unnamed2__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Init__Unnamed1__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Init__Unnamed0__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Manual__Unnamed0__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Unnamed0__Unnamed4__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Unnamed3__Manual__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Unnamed4__Init__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Unnamed5__Manual__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Manual__Unnamed5__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Unnamed6__Manual__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Manual__Unnamed6__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Manual__Unnamed1__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Manual__Unnamed2__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Unnamed1__Unnamed4__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Unnamed2__Unnamed4__0;
extern ModelImpl::TRANSITION_ENTRY PM_ModeSwitch_TRANS_Init__Unnamed3__0;
extern ModelImpl::STATE_ENTRY PM_ModeSwitch_STATE_Unnamed0;
extern ModelImpl::STATE_ENTRY PM_ModeSwitch_STATE_Unnamed1;
extern ModelImpl::STATE_ENTRY PM_ModeSwitch_STATE_Unnamed2;
extern ModelImpl::STATE_ENTRY PM_ModeSwitch_STATE_Unnamed3;
extern ModelImpl::STATE_ENTRY PM_ModeSwitch_STATE_Unnamed4;
extern ModelImpl::STATE_ENTRY PM_ModeSwitch_STATE_Unnamed5;
extern ModelImpl::STATE_ENTRY PM_ModeSwitch_STATE_Unnamed6;
extern ModelImpl::STATE_ENTRY PM_ModeSwitch_STATE_Manual;
extern ModelImpl::STATE_ENTRY PM_ModeSwitch_STATE_Init;
extern ModelImpl::PROCESS_ENTRY PM_ModeSwitch_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE PM_ModeSwitch_PROCESS_STATE;


// Process - PM_Sensor_A

extern ModelImpl::TRANSITION_ENTRY PM_Sensor_A_TRANS_Aevent__ResetClk__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_A_TRANS_Await__Aevent__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_A_TRANS_Wait_URI__Await__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_A_TRANS_Wait_PVARP__Wait_URI__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_A_TRANS_VEvent__Wait_PVARP__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_A_TRANS_WaitAVI__VEvent__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_A_TRANS_WaitAVI__VEvent__1;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_A_TRANS_ResetClk__WaitAVI__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_A_TRANS_Await__ResetClk__0;
extern ModelImpl::STATE_ENTRY PM_Sensor_A_STATE_Aevent;
extern ModelImpl::STATE_ENTRY PM_Sensor_A_STATE_Wait_URI;
extern ModelImpl::STATE_ENTRY PM_Sensor_A_STATE_Wait_PVARP;
extern ModelImpl::STATE_ENTRY PM_Sensor_A_STATE_VEvent;
extern ModelImpl::STATE_ENTRY PM_Sensor_A_STATE_WaitAVI;
extern ModelImpl::STATE_ENTRY PM_Sensor_A_STATE_ResetClk;
extern ModelImpl::STATE_ENTRY PM_Sensor_A_STATE_Await;
extern ModelImpl::PROCESS_ENTRY PM_Sensor_A_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE PM_Sensor_A_PROCESS_STATE;


// Process - PM_Sensor_V

extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_PVC__Init__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_Init__PVC__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_Unnamed7__VEvent__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_WaitVEvent__Unnamed7__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_DoneVRP__Init__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_WaitVRP__DoneVRP__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_VEvent__WaitVRP__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_WaitVEvent__VEvent__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_Wait_PVAB__WaitVEvent__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_Init_PVAB__Wait_PVAB__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_Init__Init_PVAB__0;
extern ModelImpl::TRANSITION_ENTRY PM_Sensor_V_TRANS_Init__Init_PVAB__1;
extern ModelImpl::STATE_ENTRY PM_Sensor_V_STATE_PVC;
extern ModelImpl::STATE_ENTRY PM_Sensor_V_STATE_Unnamed7;
extern ModelImpl::STATE_ENTRY PM_Sensor_V_STATE_DoneVRP;
extern ModelImpl::STATE_ENTRY PM_Sensor_V_STATE_WaitVRP;
extern ModelImpl::STATE_ENTRY PM_Sensor_V_STATE_VEvent;
extern ModelImpl::STATE_ENTRY PM_Sensor_V_STATE_WaitVEvent;
extern ModelImpl::STATE_ENTRY PM_Sensor_V_STATE_Wait_PVAB;
extern ModelImpl::STATE_ENTRY PM_Sensor_V_STATE_Init_PVAB;
extern ModelImpl::STATE_ENTRY PM_Sensor_V_STATE_Init;
extern ModelImpl::PROCESS_ENTRY PM_Sensor_V_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE PM_Sensor_V_PROCESS_STATE;


// Process - PM_Pacer_AA

extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_PaceV__Vevent__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_Adone__PMManualMode__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_PaceA__PMManualMode__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_PVC__PMManualMode__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_Vevent__PMManualMode__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_AVI_Wait__PMManualMode__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_PMManualMode__AVI_Wait__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_PVC__Adone__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_PaceA__Adone__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_Adone__AVI_Wait__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_Vevent__Adone__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_PVC__PaceA__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_Vevent__PVC__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_Vevent__PaceA__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_AVI_Wait__Vevent__0;
extern ModelImpl::TRANSITION_ENTRY PM_Pacer_AA_TRANS_AVI_Wait__PaceV__0;
extern ModelImpl::STATE_ENTRY PM_Pacer_AA_STATE_PaceV;
extern ModelImpl::STATE_ENTRY PM_Pacer_AA_STATE_PMManualMode;
extern ModelImpl::STATE_ENTRY PM_Pacer_AA_STATE_Adone;
extern ModelImpl::STATE_ENTRY PM_Pacer_AA_STATE_PVC;
extern ModelImpl::STATE_ENTRY PM_Pacer_AA_STATE_PaceA;
extern ModelImpl::STATE_ENTRY PM_Pacer_AA_STATE_Vevent;
extern ModelImpl::STATE_ENTRY PM_Pacer_AA_STATE_AVI_Wait;
extern ModelImpl::PROCESS_ENTRY PM_Pacer_AA_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE PM_Pacer_AA_PROCESS_STATE;


// Process - PM_Leds_Apace

extern ModelImpl::TRANSITION_ENTRY PM_Leds_Apace_TRANS_On__Off__0;
extern ModelImpl::TRANSITION_ENTRY PM_Leds_Apace_TRANS_Off__On__0;
extern ModelImpl::STATE_ENTRY PM_Leds_Apace_STATE_On;
extern ModelImpl::STATE_ENTRY PM_Leds_Apace_STATE_Off;
extern ModelImpl::PROCESS_ENTRY PM_Leds_Apace_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE PM_Leds_Apace_PROCESS_STATE;


// Process - PM_Leds_Asense

extern ModelImpl::TRANSITION_ENTRY PM_Leds_Asense_TRANS_On__Off__0;
extern ModelImpl::TRANSITION_ENTRY PM_Leds_Asense_TRANS_Off__On__0;
extern ModelImpl::STATE_ENTRY PM_Leds_Asense_STATE_On;
extern ModelImpl::STATE_ENTRY PM_Leds_Asense_STATE_Off;
extern ModelImpl::PROCESS_ENTRY PM_Leds_Asense_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE PM_Leds_Asense_PROCESS_STATE;


// Process - PM_Leds_Vpace

extern ModelImpl::TRANSITION_ENTRY PM_Leds_Vpace_TRANS_On__Off__0;
extern ModelImpl::TRANSITION_ENTRY PM_Leds_Vpace_TRANS_Off__On__0;
extern ModelImpl::STATE_ENTRY PM_Leds_Vpace_STATE_On;
extern ModelImpl::STATE_ENTRY PM_Leds_Vpace_STATE_Off;
extern ModelImpl::PROCESS_ENTRY PM_Leds_Vpace_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE PM_Leds_Vpace_PROCESS_STATE;


// Process - PM_Leds_Vsense

extern ModelImpl::TRANSITION_ENTRY PM_Leds_Vsense_TRANS_On__Off__0;
extern ModelImpl::TRANSITION_ENTRY PM_Leds_Vsense_TRANS_Off__On__0;
extern ModelImpl::STATE_ENTRY PM_Leds_Vsense_STATE_On;
extern ModelImpl::STATE_ENTRY PM_Leds_Vsense_STATE_Off;
extern ModelImpl::PROCESS_ENTRY PM_Leds_Vsense_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE PM_Leds_Vsense_PROCESS_STATE;


// Process - PM_DisplayAndAlarm

extern ModelImpl::TRANSITION_ENTRY PM_DisplayAndAlarm_TRANS_ShowRate__Init__0;
extern ModelImpl::TRANSITION_ENTRY PM_DisplayAndAlarm_TRANS_ShowRate__Init__1;
extern ModelImpl::TRANSITION_ENTRY PM_DisplayAndAlarm_TRANS_ShowRate__Init__2;
extern ModelImpl::TRANSITION_ENTRY PM_DisplayAndAlarm_TRANS_ShowRate__Init__3;
extern ModelImpl::TRANSITION_ENTRY PM_DisplayAndAlarm_TRANS_Init__ShowRate__0;
extern ModelImpl::TRANSITION_ENTRY PM_DisplayAndAlarm_TRANS_Incr__Init__0;
extern ModelImpl::TRANSITION_ENTRY PM_DisplayAndAlarm_TRANS_Init__Incr__0;
extern ModelImpl::TRANSITION_ENTRY PM_DisplayAndAlarm_TRANS_Init__Incr__1;
extern ModelImpl::STATE_ENTRY PM_DisplayAndAlarm_STATE_ShowRate;
extern ModelImpl::STATE_ENTRY PM_DisplayAndAlarm_STATE_Incr;
extern ModelImpl::STATE_ENTRY PM_DisplayAndAlarm_STATE_Init;
extern ModelImpl::PROCESS_ENTRY PM_DisplayAndAlarm_PROCESS;
extern ModelImpl::PROCESS_ENTRY_STATE PM_DisplayAndAlarm_PROCESS_STATE;



} // namespace

// initialize the dispatcher:
//    ModelImpl::Dispatcher disp;
//    disp.set_clock_multiplier(1000 /*us*/);
//    #ifdef DISPATCH_DEBUG
//    disp.init_debug(&pc);
//    #endif
//
// add events. examples:
//    disp.set_channel_action(&Model::Template_CHANNEL_VAR_led, LED1, ModelImpl::SendChannelModePulseUp, 250000);
//    disp.set_channel_action(&Model::Template_CHANNEL_VAR_manual, LED1, ModelImpl::SendChannelModeToggle);
//    disp.set_receive_input(&Model::GLOBAL_CHANNEL_VAR_press, p7, ModelImpl::ReceiveChannelInterruptRise);
//
// Tip: use just the templates you want in the code:
//    disp.add_process(&Model::PM_ModeSwitch_PROCESS_STATE);
//    disp.add_process(&Model::PM_Sensor_A_PROCESS_STATE);
//    disp.add_process(&Model::PM_Sensor_V_PROCESS_STATE);
//    disp.add_process(&Model::PM_Pacer_AA_PROCESS_STATE);
//    disp.add_process(&Model::PM_Leds_Apace_PROCESS_STATE);
//    disp.add_process(&Model::PM_Leds_Asense_PROCESS_STATE);
//    disp.add_process(&Model::PM_Leds_Vpace_PROCESS_STATE);
//    disp.add_process(&Model::PM_Leds_Vsense_PROCESS_STATE);
//    disp.add_process(&Model::PM_DisplayAndAlarm_PROCESS_STATE);
//
// and finally run:
//    disp.run();

